/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RFfz8eqROxt
 */
import { Label } from "~/components/ui/label"
import { Input } from "~/components/ui/input"
import { Textarea } from "~/components/ui/textarea"
import { Button } from "~/components/ui/button"
import { CardTitle, CardHeader, CardContent, Card } from "~/components/ui/card"

export function RecipeCreate() {
  return (
    <div className="grid gap-4 md:gap-8">
      <h1 className="font-semibold text-lg md:text-2xl">Add New Recipe</h1>
      <form className="grid gap-4 md:gap-8">
        <div className="grid gap-2">
          <Label htmlFor="title">Title</Label>
          <Input id="title" placeholder="Enter recipe title" />
        </div>
        <div className="grid gap-2">
          <Label htmlFor="ingredients">Ingredients</Label>
          <Textarea id="ingredients" placeholder="Enter ingredients" />
        </div>
        <div className="grid gap-2">
          <Label htmlFor="instructions">Instructions</Label>
          <Textarea id="instructions" placeholder="Enter instructions" />
        </div>
        <div className="grid gap-2">
          <Label htmlFor="cooking-time">Cooking Time</Label>
          <Input id="cooking-time" placeholder="Enter cooking time" />
        </div>
        <Button className="ml-auto" size="sm">
          Add Recipe
        </Button>
      </form>
    </div>
  )
}
